import YAML from 'yaml';
import path from 'node:path';
import fs from 'node:fs';
import { log } from './utils/logger.js';
import { readFileSafe, listFiles } from './utils/fs.js';
import { requireInit } from './config.js';
import { calculateTeamHealth } from './skill-health.js';
import type { GlobalOptions, UserStats } from './types.js';

// ─── Weekly Team Digest ────────────────────────────────
//
//  teamai digest
//      │
//      ▼
//  [read team stats from stats/*.yaml]
//      │
//      ▼
//  [read sessions from sessions/*/*.md]
//      │
//      ▼
//  [generate formatted weekly summary]
//

/**
 * Load all team stats from the repo's stats/ directory.
 */
async function loadTeamStats(repoPath: string): Promise<UserStats[]> {
  const statsDir = path.join(repoPath, 'stats');
  const stats: UserStats[] = [];

  try {
    const files = await listFiles(statsDir);
    for (const file of files) {
      if (!file.endsWith('.yaml') && !file.endsWith('.yml')) continue;
      const content = await readFileSafe(path.join(statsDir, file));
      if (!content) continue;
      try {
        const parsed = YAML.parse(content) as UserStats;
        if (parsed?.username && parsed?.skills) {
          stats.push(parsed);
        }
      } catch {
        log.debug(`Skipping invalid stats file: ${file}`);
      }
    }
  } catch {
    // stats/ dir doesn't exist yet
  }

  return stats;
}

/**
 * Get session summaries from the past week.
 */
async function getRecentSessions(repoPath: string): Promise<string[]> {
  const sessionsDir = path.join(repoPath, 'sessions');
  const summaries: string[] = [];

  try {
    const userDirs = await fs.promises.readdir(sessionsDir, { withFileTypes: true });
    for (const userDir of userDirs) {
      if (!userDir.isDirectory()) continue;
      const userSessionsDir = path.join(sessionsDir, userDir.name);
      const files = await listFiles(userSessionsDir);
      for (const file of files) {
        if (!file.endsWith('.md')) continue;
        const content = await readFileSafe(path.join(userSessionsDir, file));
        if (content) {
          // Extract session entries (simplified: just grab content)
          summaries.push(`[${userDir.name}] ${file}:\n${content.slice(0, 500)}`);
        }
      }
    }
  } catch {
    // sessions/ doesn't exist yet
  }

  return summaries;
}

/**
 * Generate and display weekly team digest.
 */
export async function generateDigest(options: GlobalOptions): Promise<void> {
  try {
    const { localConfig } = await requireInit();
    const repoPath = localConfig.repo.localPath;

    const teamStats = await loadTeamStats(repoPath);

    if (teamStats.length === 0) {
      console.log('No team usage data available yet.');
      console.log('Usage data is collected automatically and reported during `teamai pull`.');
      return;
    }

    const health = calculateTeamHealth(teamStats);
    const sessions = await getRecentSessions(repoPath);

    // Header
    const now = new Date();
    const weekStart = new Date(now.getTime() - 7 * 86_400_000);
    console.log('');
    console.log('╔════════════════════════════════════════════════════╗');
    console.log('║           📊 Team AI Weekly Digest                ║');
    console.log(`║  ${weekStart.toISOString().slice(0, 10)} → ${now.toISOString().slice(0, 10)}                        ║`);
    console.log('╚════════════════════════════════════════════════════╝');
    console.log('');

    // Team members active
    console.log(`👥 Active members: ${teamStats.length}`);
    console.log('');

    // Most used skills
    console.log('🏆 Most Used Skills:');
    for (const item of health.slice(0, 10)) {
      console.log(`  ${item.stars}  ${item.skill} (${item.totalCount} uses by ${item.contributors} member(s))`);
    }
    console.log('');

    // Total events
    const totalEvents = teamStats.reduce(
      (sum, u) => sum + Object.values(u.skills).reduce((s, sk) => s + sk.count, 0),
      0,
    );
    console.log(`📈 Total skill invocations: ${totalEvents}`);
    console.log(`🔧 Unique skills used: ${health.length}`);
    console.log('');

    // Session highlights
    if (sessions.length > 0) {
      console.log('📝 Session Highlights:');
      for (const session of sessions.slice(0, 5)) {
        console.log(`  ${session.slice(0, 120)}...`);
      }
      console.log('');
    }

    console.log('─'.repeat(52));
    console.log('Generated by teamai digest');
  } catch (e) {
    log.error(`Failed to generate digest: ${(e as Error).message}`);
  }
}
